export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Softwareentwicklung',
    headLine:"WIR ENTWICKLEN MIT MODERNEN TECHNOLOGIEN", 
    description:'Für Ihre Software gibt es viele Anforderungen? Sie soll sicher, produktiv, gut bedienbar, schön, performant und verfügbar sein und natürlich dem Datenschutz gerecht werden? Unser Angebot ist so individuell wie Ihre Herausforderungen. Wir haben immer die passende Lösung für Sie.',
    buttonLabel:'Mehr',
    imgStart:false,
    img:require("../../images/svg-1.svg")?.default,
    alt:'Programmer',
    dark:true,
    primary:true,
    darkText:false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText:false,
    lightTextDesc:false,
    topLine:'WIR BIETEN',
    headLine:"ALLES AUS EINER HAND", 
    description:'Die KALIQI IT SOLUTIONS bietet ein vollständiges Dienstleistungsangebot rund um das Thema Software-Entwicklung Lösung über das Oberflächendesign, Usability-Konzept  und Programmierung bis zum Betrieb und Pflege der Software.',
    buttonLabel:'Mehr',
    imgStart:true,
    img:require("../../images/svg-2.svg")?.default,
    alt:'Sheet',
    dark:true,
    primary:true,
    darkText:true,
};

export const homeObjThree = {
    id: 'services',
    lightBg: false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Softwareentwicklung',
    headLine:"WIR ENTWICKLEN MIT MODERNEN TECHNOLOGIEN", 
    description:'Für Ihre Software gibt es viele Anforderungen? Sie soll sicher, produktiv, gut bedienbar, schön, performant und verfügbar sein und natürlich dem Datenschutz gerecht werden? Unser Angebot ist so individuell wie Ihre Herausforderungen. Wir haben immer die passende Lösung für Sie.',
    buttonLabel:'Mehr',
    imgStart:false,
    img:require('../../images/svg-3.svg')?.default,
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}